//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiAdventure.LevelBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YetiAdventure.LevelBuilder.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brush.
        /// </summary>
        public static string BrushTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("BrushTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas size:.
        /// </summary>
        public static string CanvasSize {
            get {
                return ResourceManager.GetString("CanvasSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas size.
        /// </summary>
        public static string editmenu_canvassize {
            get {
                return ResourceManager.GetString("editmenu_canvassize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string editmenu_setting {
            get {
                return ResourceManager.GetString("editmenu_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string editmenucaption {
            get {
                return ResourceManager.GetString("editmenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eraser.
        /// </summary>
        public static string EmptyTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("EmptyTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event trigger brush.
        /// </summary>
        public static string EventTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("EventTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string eventtilecaption {
            get {
                return ResourceManager.GetString("eventtilecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ExceptionDialogTitle {
            get {
                return ResourceManager.GetString("ExceptionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Project.
        /// </summary>
        public static string exportDialogTitle {
            get {
                return ResourceManager.GetString("exportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lpfx.
        /// </summary>
        public static string exportedExtension {
            get {
                return ResourceManager.GetString("exportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Package File.
        /// </summary>
        public static string exportedFileType {
            get {
                return ResourceManager.GetString("exportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close project.
        /// </summary>
        public static string filemenu_close {
            get {
                return ResourceManager.GetString("filemenu_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string filemenu_exit {
            get {
                return ResourceManager.GetString("filemenu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string filemenu_export {
            get {
                return ResourceManager.GetString("filemenu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string filemenu_new {
            get {
                return ResourceManager.GetString("filemenu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string filemenu_open {
            get {
                return ResourceManager.GetString("filemenu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string filemenu_save {
            get {
                return ResourceManager.GetString("filemenu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save as.
        /// </summary>
        public static string filemenu_saveas {
            get {
                return ResourceManager.GetString("filemenu_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string filemenucaption {
            get {
                return ResourceManager.GetString("filemenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fill tool.
        /// </summary>
        public static string FillBucketTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("FillBucketTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string helpmenu_about {
            get {
                return ResourceManager.GetString("helpmenu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation.
        /// </summary>
        public static string helpmenu_documentation {
            get {
                return ResourceManager.GetString("helpmenu_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string helpmenucaption {
            get {
                return ResourceManager.GetString("helpmenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to backdrop.
        /// </summary>
        public static string LayerLabel_Backdrop {
            get {
                return ResourceManager.GetString("LayerLabel_Backdrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to background.
        /// </summary>
        public static string LayerLabel_Background {
            get {
                return ResourceManager.GetString("LayerLabel_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreground.
        /// </summary>
        public static string LayerLabel_Foreground {
            get {
                return ResourceManager.GetString("LayerLabel_Foreground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to middleground.
        /// </summary>
        public static string LayerLabel_Middleground {
            get {
                return ResourceManager.GetString("LayerLabel_Middleground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lev.config.
        /// </summary>
        public static string levelconfigurationextension {
            get {
                return ResourceManager.GetString("levelconfigurationextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apply changes.
        /// </summary>
        public static string LevelDetails_ApplyChanges_ToolTip {
            get {
                return ResourceManager.GetString("LevelDetails_ApplyChanges_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse for tile set.
        /// </summary>
        public static string LevelDetails_BrowseForTileSet_ToolTip {
            get {
                return ResourceManager.GetString("LevelDetails_BrowseForTileSet_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level details.
        /// </summary>
        public static string LevelDetails_Header {
            get {
                return ResourceManager.GetString("LevelDetails_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to level name:.
        /// </summary>
        public static string LevelDetails_LevelName_Label {
            get {
                return ResourceManager.GetString("LevelDetails_LevelName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile sheet:.
        /// </summary>
        public static string LevelDetails_TileSet_Label {
            get {
                return ResourceManager.GetString("LevelDetails_TileSet_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile size:.
        /// </summary>
        public static string LevelDetails_TileSize_Label {
            get {
                return ResourceManager.GetString("LevelDetails_TileSize_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lev.
        /// </summary>
        public static string levellayoutextension {
            get {
                return ResourceManager.GetString("levellayoutextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to end.
        /// </summary>
        public static string LevelTest_EndTest {
            get {
                return ResourceManager.GetString("LevelTest_EndTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to preview.
        /// </summary>
        public static string LevelTest_StartTest {
            get {
                return ResourceManager.GetString("LevelTest_StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas height:.
        /// </summary>
        public static string NewProject_CanvasHeight {
            get {
                return ResourceManager.GetString("NewProject_CanvasHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas width:.
        /// </summary>
        public static string NewProject_CanvasWidth {
            get {
                return ResourceManager.GetString("NewProject_CanvasWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ok.
        /// </summary>
        public static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to output.
        /// </summary>
        public static string OutputDirectoryName {
            get {
                return ResourceManager.GetString("OutputDirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile picker.
        /// </summary>
        public static string PickerTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("PickerTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pixels.
        /// </summary>
        public static string Pixels_Label {
            get {
                return ResourceManager.GetString("Pixels_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lvlp.
        /// </summary>
        public static string projectFileExtension {
            get {
                return ResourceManager.GetString("projectFileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Builder Project File.
        /// </summary>
        public static string projectFileTypeName {
            get {
                return ResourceManager.GetString("projectFileTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start position brush.
        /// </summary>
        public static string StartTileBrush_ToolTip {
            get {
                return ResourceManager.GetString("StartTileBrush_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        public static string starttilecaption {
            get {
                return ResourceManager.GetString("starttilecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string StatusUpdate_LoadingFile {
            get {
                return ResourceManager.GetString("StatusUpdate_LoadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning. tile size is too small or file does not exist. cannot proceed.
        /// </summary>
        public static string TilePalette_EmptyWarning {
            get {
                return ResourceManager.GetString("TilePalette_EmptyWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning. tile size exceeds sheet dimensions. some tiles may have been cropped.
        /// </summary>
        public static string TilePalette_ExceedsWarning {
            get {
                return ResourceManager.GetString("TilePalette_ExceedsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning. tile size exceeds sheet dimensions. some tiles may have been cropped.
        /// </summary>
        public static string TilePalette_ExceedsWarning1 {
            get {
                return ResourceManager.GetString("TilePalette_ExceedsWarning1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tile palette.
        /// </summary>
        public static string TilePalette_Header {
            get {
                return ResourceManager.GetString("TilePalette_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tiles.
        /// </summary>
        public static string Tiles_Label {
            get {
                return ResourceManager.GetString("Tiles_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tilesheet.
        /// </summary>
        public static string TileSheetName {
            get {
                return ResourceManager.GetString("TileSheetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to event manager.
        /// </summary>
        public static string viewmenu_eventmanager {
            get {
                return ResourceManager.GetString("viewmenu_eventmanager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grid lines.
        /// </summary>
        public static string viewmenu_gridlines {
            get {
                return ResourceManager.GetString("viewmenu_gridlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string viewmenucaption {
            get {
                return ResourceManager.GetString("viewmenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to projects.
        /// </summary>
        public static string WorkingProjectDirectoryName {
            get {
                return ResourceManager.GetString("WorkingProjectDirectoryName", resourceCulture);
            }
        }
    }
}
