//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YetiAdventure.LevelBuilder.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("YetiAdventure.LevelBuilder.Resources.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas.
        /// </summary>
        public static string Controls_LevelCanvasControl_Header {
            get {
                return ResourceManager.GetString("Controls_LevelCanvasControl_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolbox.
        /// </summary>
        public static string Controls_ToolboxControl_Header {
            get {
                return ResourceManager.GetString("Controls_ToolboxControl_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selection tool.
        /// </summary>
        public static string Controls_ToolboxItem_Cursor_Caption {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_Cursor_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selects object.
        /// </summary>
        public static string Controls_ToolboxItem_Cursor_Tooltip {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_Cursor_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to polygon tool.
        /// </summary>
        public static string Controls_ToolboxItem_Polygon_Caption {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_Polygon_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draws polygons.
        /// </summary>
        public static string Controls_ToolboxItem_Polygon_Tooltip {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_Polygon_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to move tool.
        /// </summary>
        public static string Controls_ToolboxItem_SelectionMove_Caption {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_SelectionMove_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to moves objects.
        /// </summary>
        public static string Controls_ToolboxItem_SelectionMove_Tooltip {
            get {
                return ResourceManager.GetString("Controls_ToolboxItem_SelectionMove_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to canvas size.
        /// </summary>
        public static string editmenu_canvassize {
            get {
                return ResourceManager.GetString("editmenu_canvassize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string editmenu_setting {
            get {
                return ResourceManager.GetString("editmenu_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string editmenucaption {
            get {
                return ResourceManager.GetString("editmenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !.
        /// </summary>
        public static string eventtilecaption {
            get {
                return ResourceManager.GetString("eventtilecaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        public static string ExceptionDialogTitle {
            get {
                return ResourceManager.GetString("ExceptionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Project.
        /// </summary>
        public static string exportDialogTitle {
            get {
                return ResourceManager.GetString("exportDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lpfx.
        /// </summary>
        public static string exportedExtension {
            get {
                return ResourceManager.GetString("exportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Package File.
        /// </summary>
        public static string exportedFileType {
            get {
                return ResourceManager.GetString("exportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to close project.
        /// </summary>
        public static string filemenu_close {
            get {
                return ResourceManager.GetString("filemenu_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exit.
        /// </summary>
        public static string filemenu_exit {
            get {
                return ResourceManager.GetString("filemenu_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string filemenu_export {
            get {
                return ResourceManager.GetString("filemenu_export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new.
        /// </summary>
        public static string filemenu_new {
            get {
                return ResourceManager.GetString("filemenu_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string filemenu_open {
            get {
                return ResourceManager.GetString("filemenu_open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string filemenu_save {
            get {
                return ResourceManager.GetString("filemenu_save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save as.
        /// </summary>
        public static string filemenu_saveas {
            get {
                return ResourceManager.GetString("filemenu_saveas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string filemenucaption {
            get {
                return ResourceManager.GetString("filemenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string helpmenu_about {
            get {
                return ResourceManager.GetString("helpmenu_about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to documentation.
        /// </summary>
        public static string helpmenu_documentation {
            get {
                return ResourceManager.GetString("helpmenu_documentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to help.
        /// </summary>
        public static string helpmenucaption {
            get {
                return ResourceManager.GetString("helpmenucaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .lev.
        /// </summary>
        public static string levellayoutextension {
            get {
                return ResourceManager.GetString("levellayoutextension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grid lines.
        /// </summary>
        public static string viewmenu_gridlines {
            get {
                return ResourceManager.GetString("viewmenu_gridlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view.
        /// </summary>
        public static string viewmenucaption {
            get {
                return ResourceManager.GetString("viewmenucaption", resourceCulture);
            }
        }
    }
}
